# Generated by Django 3.0 on 2022-12-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
