# Generated by Django 3.0 on 2022-12-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
