# Generated by Django 3.0 on 2022-12-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20221226_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='current_bid',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='number_of_bids',
            field=models.IntegerField(null=True),
        ),
    ]
