# Generated by Django 3.0 on 2022-12-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20221228_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='number_of_bids',
            field=models.IntegerField(default=0),
        ),
    ]
