# Generated by Django 3.0 on 2022-12-29 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20221229_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='item_id',
            new_name='item',
        ),
    ]
